### ISSUE TITLE
Iron Clad Bonus

### ISSUE THREAD

**Issue by uc9089** [Otari98/BetterCharacterStats#8]
`function BCS:IronClad(statFrame)

	local frame = statFrame
	local label = getglobal(frame:GetName() .. "Label")
	local text = getglobal(frame:GetName() .. "StatText")
	local base, effectiveArmor, armor, posBuff, negBuff = UnitArmor("player")
	local totalBufs = posBuff + negBuff
	PaperDollFormatStat(ARMOR, base, posBuff, negBuff, frame, text)
	

	local ironCladHealing = base * 0.02
	label:SetText("Healing w/IC")
	local power, _, _, dmg = BCS:GetSpellPower()
	local heal, treebonus = BCS:GetHealingPower()
	power = power - dmg
	local total = power + heal + ironCladHealing
	if treebonus and aura[1] <= treebonus then
		total = total + treebonus
	elseif (not treebonus and aura[1] > 0) or (treebonus and aura[1] > treebonus) then
		total = total + aura[1]
	end
	text:SetText(format("%.f", total))
	if heal ~= 0 then
		frame.tooltip = format(ironCladHealing)
	else
		frame.tooltip = format(L.SPELL_IRONCLAD_TOOLTIP, (total), ironCladHealing)
	end
	frame.tooltipSubtext = format(L.SPELL_IRONCLAD_TOOLTIP_SUB, ironCladHealing)

	BCS:AddTooltip(frame)

end`

**Comment by uc9089** [comment]
`elseif (index == "PLAYERSTAT_SPELL_COMBAT") then
		BCS:SetSpellPower(stat1)
		BCS:SetRating(stat2, "SPELL")
		BCS:SetSpellCritChance(stat3)
		BCS:SetHealing(stat4)
		BCS:SetManaRegen(stat5)
		BCS:IronClad(stat6)`


adding in dropdown menu of spell

**Comment by Otari98** [comment]
BCS:GetHealingPower() already includes this talent
ironCladHealing = base * 0.02 is incorrect, because base includes armor from agility
Adding line in spell tab that works only for paladins, only with 1 talent is stupid, i can see it as neat little bonus line on a healing tooltip if you have this talent, but not the separate line in the tab...
If you want to contribute you should use pull requests
